import 'translation_keys.dart';

const Map<String, String> ar = {
  TranslationKeys.home: 'الرئيسية',
  TranslationKeys.categories: 'الأقسام',
  TranslationKeys.brands: 'الماركات',
  TranslationKeys.discountedProducts: 'عروض مميزة',
  TranslationKeys.newArrivals: 'وصل حديثاً',
  TranslationKeys.topSelling: 'الأكثر مبيعاً',
  TranslationKeys.logIn: 'تسجيل الدخول',
  TranslationKeys.shopNow: 'تسوق الآن',
  TranslationKeys.about: 'من نحن',
  TranslationKeys.contactUs: 'تواصل معنا',
  TranslationKeys.termsConditions: 'الشروط والأحكام',
  TranslationKeys.privacyPolicy: 'سياسة الخصوصية',
  TranslationKeys.help: 'مساعدة',
  TranslationKeys.search: 'بحث',
  
  // Offers and Coupons
  TranslationKeys.couponCode: 'كود الخصم',
  TranslationKeys.specialOffers: 'عروض مميزة',
  TranslationKeys.offers: 'العروض',
  TranslationKeys.topBundles: 'أفضل الباقات',
  TranslationKeys.couponsAndDiscounts: 'كوبونات وخصومات',
  TranslationKeys.specialDeals: 'صفقات مميزة',

  // Auth section
  TranslationKeys.welcomeBack: 'مرحباً بعودتك',
  TranslationKeys.pleaseEnterDetailsToSignIn: 'يرجى إدخال بياناتك لتسجيل الدخول.',
  TranslationKeys.email: 'البريد الإلكتروني',
  TranslationKeys.enterYourEmail: 'أدخل بريدك الإلكتروني',
  TranslationKeys.emailRequired: 'البريد الإلكتروني مطلوب',
  TranslationKeys.password: 'كلمة المرور',
  TranslationKeys.enterYourPassword: 'أدخل كلمة المرور',
  TranslationKeys.passwordRequired: 'كلمة المرور مطلوبة',
  TranslationKeys.rememberMe: 'تذكرني',
  TranslationKeys.forgotPassword: 'نسيت كلمة المرور',
  TranslationKeys.loginFailed: 'فشل تسجيل الدخول',
  TranslationKeys.signIn: 'تسجيل الدخول',
  TranslationKeys.dontHaveAccount: 'ليس لديك حساب؟ ',
  TranslationKeys.signUp: 'إنشاء حساب',
  
  TranslationKeys.createAccount: 'إنشاء حساب',
  TranslationKeys.pleaseEnterDetailsToSignUp: 'يرجى إدخال بياناتك لإنشاء حساب.',
  TranslationKeys.firstName: 'الاسم الأول',
  TranslationKeys.lastName: 'الاسم الأخير',
  TranslationKeys.confirmPassword: 'تأكيد كلمة المرور',
  TranslationKeys.requiredField: 'هذا الحقل مطلوب',
  TranslationKeys.createPassword: 'أنشئ كلمة مرور',
  TranslationKeys.confirmYourPassword: 'أكد كلمة المرور',
  TranslationKeys.passwordsDoNotMatch: 'كلمات المرور غير متطابقة!',
  TranslationKeys.pleaseAgreeToTerms: 'يرجى الموافقة على الشروط والأحكام',
  TranslationKeys.iAgreeToThe: 'أوافق على ',
  TranslationKeys.andPrivacyPolicy: ' وسياسة الخصوصية',
  TranslationKeys.alreadyHaveAccount: 'لديك حساب بالفعل؟ ',
  TranslationKeys.registrationFailed: 'فشل إنشاء الحساب',
  
  TranslationKeys.noWorriesResetInstructions: 'لا تقلق، سنرسل لك تعليمات الاستعادة.',
  TranslationKeys.sendResetLink: 'إرسال رابط الاستعادة',
  TranslationKeys.backToLogin: 'العودة لتسجيل الدخول',
  
  TranslationKeys.passwordReset: 'تم تغيير كلمة المرور',
  TranslationKeys.passwordResetSuccessMessage: 'تم إعادة تعيين كلمة المرور بنجاح. اضغط أدناه لتسجيل الدخول.',
  TranslationKeys.continueToLogin: 'المتابعة لتسجيل الدخول',
  TranslationKeys.setNewPassword: 'تعيين كلمة مرور جديدة',
  TranslationKeys.newPasswordMustBeDifferent: 'يجب أن تكون كلمة المرور الجديدة مختلفة عن السابقة.',
  TranslationKeys.mustBeAtLeast8: 'يجب أن تتكون من 8 أحرف على الأقل',
  TranslationKeys.bothPasswordsMustMatch: 'يجب أن تتطابق كلتا الكلمتين',
  TranslationKeys.resetPassword: 'إعادة تعيين كلمة المرور',
  
  TranslationKeys.orContinueWith: 'أو المتابعة باستخدام',
  
  // Profile section
  TranslationKeys.myAccount: 'حسابي',
  TranslationKeys.orders: 'الطلبات',
  TranslationKeys.wishlist: 'المفضلة',
  TranslationKeys.addresses: 'العناوين',
  TranslationKeys.settings: 'الإعدادات',
  TranslationKeys.logout: 'تسجيل الخروج',
  TranslationKeys.switchStore: 'تغيير المتجر',
  TranslationKeys.myStores: 'متاجري',
  TranslationKeys.visits: 'الزيارات',
  TranslationKeys.ordersCount: 'الطلبيات',
  TranslationKeys.sectionComingSoon: 'هذا القسم سيكون متاحاً قريباً!',
  TranslationKeys.profileUpdatedSuccessfully: 'تم تحديث البروفايل بنجاح!',
  TranslationKeys.accountInformation: 'معلومات الحساب',
  TranslationKeys.updateYourPersonalInfo: 'قم بتحديث معلوماتك الشخصية أدناه.',
  TranslationKeys.enterYourFirstName: 'أدخل اسمك الأول',
  TranslationKeys.enterYourLastName: 'أدخل اسمك الأخير',
  TranslationKeys.emailAddress: 'البريد الإلكتروني',
  TranslationKeys.phoneNumber: 'رقم الهاتف',
  TranslationKeys.enterYourPhoneNumber: 'أدخل رقم هاتفك',
  TranslationKeys.saveChanges: 'حفظ التغييرات',
  
  TranslationKeys.orderHistory: 'تاريخ الطلبات',
  TranslationKeys.viewYourRecentOrders: 'عرض طلباتك الحديثة وحالتها.',
  TranslationKeys.noOrdersYet: 'لا توجد طلبات بعد',
  TranslationKeys.yourRecentOrdersWillAppearHere: 'ستظهر طلباتك الحديثة هنا',
  TranslationKeys.statusDelivered: 'تم التوصيل',
  TranslationKeys.statusProcessing: 'قيد المعالجة',
  TranslationKeys.statusCancelled: 'ملغى',
  TranslationKeys.viewDetails: 'عرض التفاصيل',

  TranslationKeys.myWishlist: 'مفضلتي',
  TranslationKeys.productsYouHaveSavedForLater: 'المنتجات التي قمت بحفظها لوقت لاحق.',
  TranslationKeys.yourWishlistIsEmpty: 'مفضلتك فارغة',
  TranslationKeys.tapHeartToSave: 'اضغط على أيقونة القلب على أي منتج لحفظه.',

  TranslationKeys.savedAddresses: 'العناوين المحفوظة',
  TranslationKeys.manageShippingAndBilling: 'إدارة عناوين الشحن والدفع.',
  TranslationKeys.noAddressesFound: 'لا توجد عناوين',
  TranslationKeys.addNewAddressPrompt: 'أضف عنوان جديد لإتمام الشراء أسرع',
  TranslationKeys.addNew: '+ إضافة جديد',

  TranslationKeys.appearance: 'المظهر',
  TranslationKeys.theme: 'السمة',
  TranslationKeys.selectApplicationTheme: 'اختر سمة التطبيق',
  TranslationKeys.systemDefault: 'افتراضي النظام',
  TranslationKeys.light: 'فاتح',
  TranslationKeys.dark: 'داكن',
  
  TranslationKeys.localization: 'الترجمة',
  TranslationKeys.language: 'اللغة',
  TranslationKeys.selectApplicationLanguage: 'اختر لغة التطبيق',
  TranslationKeys.english: 'English',
  TranslationKeys.arabic: 'العربية',
  
  TranslationKeys.regional: 'الإقليمية',
  TranslationKeys.currency: 'العملة',
  TranslationKeys.selectPreferredCurrency: 'اختر العملة المفضلة',

  TranslationKeys.profile: 'الملف الشخصي',
  TranslationKeys.menu: 'القائمة',
  TranslationKeys.items: 'عناصر',

  TranslationKeys.byAlzakaaSimpleSolutionsAllRightsReserved: 'بواسطة الذكاء للحلول البسيطة، جميع الحقوق محفوظة',

  // Home Page
  TranslationKeys.findClothesThatMatchesYourStyle: 'ابحث عن الملابس التي تناسب أسلوبك',
  TranslationKeys.browseThroughOurDiverseRange: 'تصفح من خلال مجموعتنا المتنوعة من الملابس المصنوعة بدقة، والمصممة لإبراز شخصيتك وتلبية ذوقك الخاص.',
  TranslationKeys.fashionModel: 'عارض أزياء',
  TranslationKeys.browseByCategory: 'تصفح حسب القسم',
  TranslationKeys.viewAll: 'عرض الكل',
  TranslationKeys.stayUptoDate: 'ابق على اطلاع بأحدث عروضنا',
  TranslationKeys.subscribeToNewsletter: 'الاشتراك في النشرة الإخبارية',
  TranslationKeys.subscribedSuccessfully: 'تم الاشتراك في النشرة الإخبارية بنجاح!',
  TranslationKeys.pleaseLoginToSaveItems: 'يرجى تسجيل الدخول لحفظ المنتجات في المفضلة.',

  // Categories & Product Details
  TranslationKeys.allProducts: 'كل المنتجات',
  TranslationKeys.productDetails: 'تفاصيل المنتج',
  TranslationKeys.shop: 'المتجر',
  TranslationKeys.showingProductsTemplate: 'عرض {start}-{end} من أصل {total} منتج',
  TranslationKeys.sortBy: 'ترتيب حسب: ',
  TranslationKeys.mostPopular: 'الأكثر شعبية',
  TranslationKeys.newest: 'الأحدث',
  TranslationKeys.priceLowToHigh: 'السعر: من الأقل للأعلى',
  TranslationKeys.priceHighToLow: 'السعر: من الأعلى للأقل',
  TranslationKeys.filters: 'الفلاتر',
  TranslationKeys.clear: 'مسح',
  TranslationKeys.price: 'السعر',
  TranslationKeys.color: 'اللون',
  TranslationKeys.colors: 'الألوان',
  TranslationKeys.noColorsAvailable: 'لا توجد ألوان متاحة',
  TranslationKeys.size: 'المقاس',
  TranslationKeys.noSizesAvailable: 'لا توجد مقاسات متاحة',
  TranslationKeys.viewInCart: 'عرض في السلة',
  TranslationKeys.addToCart: 'أضف إلى السلة',
  TranslationKeys.selectColors: 'اختر الألوان',
  TranslationKeys.chooseSize: 'اختر المقاس',
  TranslationKeys.youMightAlsoLike: 'قد يعجبك أيضاً',
  TranslationKeys.previous: 'السابق',
  TranslationKeys.next: 'التالي',
  TranslationKeys.noProductsFound: 'لم يتم العثور على منتجات في هذا القسم.',

  // Cart & Checkout
  TranslationKeys.qty: 'الكمية',
  TranslationKeys.yourCart: 'سلة مشترياتك',
  TranslationKeys.yourCartIsEmpty: 'سلة المشتريات فارغة',
  TranslationKeys.cartEmptySubtitle: 'يبدو أنك لم تقم بإضافة أي منتجات حتى الآن.',
  TranslationKeys.itemRemovedFromCart: 'تمت إزالة المنتج من السلة',
  TranslationKeys.notAvailable: 'غير متوفر',
  TranslationKeys.orderSummary: 'ملخص الطلب',
  TranslationKeys.pricingMultiplied: 'تم مضاعفة السعر بـ {multiplier} (بسبب وجود عناوين شحن متعددة)',
  TranslationKeys.subtotal: 'المجموع الفرعي',
  TranslationKeys.discount: 'خصم (20%)',
  TranslationKeys.deliveryFee: 'رسوم التوصيل',
  TranslationKeys.total: 'الإجمالي',
  TranslationKeys.placeOrder: 'إتمام الطلب',
  TranslationKeys.goToCheckout: 'الذهاب للدفع',
  TranslationKeys.checkout: 'الدفع',
  TranslationKeys.loginToPlaceOrder: 'يرجى تسجيل الدخول لإتمام الطلب.',
  TranslationKeys.selectShippingAddress: 'يرجى اختيار عنوان شحن واحد على الأقل.',
  TranslationKeys.orderPlacedSuccessfully: 'تم إرسال الطلب بنجاح!',
  TranslationKeys.thankYouForPurchase: 'شكراً لشرائك.\nأرقام الفواتير الخاصة بك:\n',
  TranslationKeys.backToHome: 'العودة للرئيسية',
  TranslationKeys.checkoutTitle: 'إتمام الشراء',
  TranslationKeys.customerInformation: 'معلومات العميل',
  TranslationKeys.checkingOutAsGuest: 'أنت تقوم بالشراء كزائر.',
  TranslationKeys.login: 'تسجيل الدخول',
  TranslationKeys.noPhoneNumber: 'لا يوجد رقم هاتف',
  TranslationKeys.shippingAddress: 'عنوان الشحن',
  TranslationKeys.loginToManageAddresses: 'يرجى تسجيل الدخول لإدارة عناوين الشحن الخاصة بك.',
  TranslationKeys.noSavedAddresses: 'لم يتم العثور على عناوين محفوظة. يرجى إضافة عنوان جديد.',
  TranslationKeys.addNewAddress: 'إضافة عنوان جديد',
  TranslationKeys.orderItems: 'عناصر الطلب ({count})',
  TranslationKeys.addressFallback: 'العنوان',
  TranslationKeys.paymentMethod: 'طريقة الدفع',
  TranslationKeys.paymentMethodCod: 'الدفع عند الاستلام',
  TranslationKeys.paymentMethodCreditCard: 'بطاقة ائتمان',
  TranslationKeys.paymentMethodPaypal: 'باي بال',

  // Address Form
  TranslationKeys.editAddress: 'تعديل العنوان',
  TranslationKeys.addressLabelOptional: 'تسمية العنوان (اختياري)',
  TranslationKeys.egHomeWork: 'مثال: المنزل، العمل',
  TranslationKeys.streetAddress: 'عنوان الشارع',
  TranslationKeys.enterStreetAddress: 'أدخل عنوان الشارع',
  TranslationKeys.city: 'المدينة',
  TranslationKeys.state: 'الولاية / المحافظة',
  TranslationKeys.zipCode: 'الرمز البريدي',
  TranslationKeys.country: 'البلد',
  TranslationKeys.requiredValidation: 'مطلوب',
  TranslationKeys.saveAddress: 'حفظ العنوان',

  // Order Details
  TranslationKeys.orderDetails: 'تفاصيل الطلب',
  TranslationKeys.orderNumber: 'طلب {id}',
  TranslationKeys.placedOn: 'تم الطلب في {date}',
  TranslationKeys.tax: 'الضريبة',
  TranslationKeys.defaultText: 'افتراضي',

  // Misc
  TranslationKeys.google: 'جوجل',
  TranslationKeys.apple: 'آبل',
  TranslationKeys.john: 'محمد',
  TranslationKeys.doe: 'أحمد',
  TranslationKeys.phone: 'الهاتف',
  TranslationKeys.contactUsDescription: 'نسعد دائماً بتواصلكم معنا! يرجى مراسلتنا عبر التفاصيل أدناه:',
  TranslationKeys.supportTeamAvailable: 'فريق الدعم الخاص بنا متاح على مدار الساعة لمساعدتك في أي استفسارات أو مخاوف.',
  TranslationKeys.selectStore: 'اختر المتجر',
  TranslationKeys.noStoresAvailable: 'لا توجد متاجر متاحة.',
};
