import 'translation_keys.dart';

const Map<String, String> en = {
  TranslationKeys.home: 'Home',
  TranslationKeys.categories: 'Categories',
  TranslationKeys.brands: 'Brands',
  TranslationKeys.discountedProducts: 'On Sale',
  TranslationKeys.newArrivals: 'New Arrivals',
  TranslationKeys.topSelling: 'Top selling',
  TranslationKeys.logIn: 'Log In',
  TranslationKeys.shopNow: 'Shop Now',
  TranslationKeys.about: 'About',
  TranslationKeys.contactUs: 'Contact Us',
  TranslationKeys.termsConditions: 'Terms & Conditions',
  TranslationKeys.privacyPolicy: 'Privacy Policy',
  TranslationKeys.help: 'Help',
  TranslationKeys.search: 'Search',
  
  // Offers and Coupons
  TranslationKeys.couponCode: 'Coupon Code',
  TranslationKeys.specialOffers: 'Special Offers',
  TranslationKeys.offers: 'Offers',
  TranslationKeys.topBundles: 'Top Bundles',
  TranslationKeys.couponsAndDiscounts: 'Coupons & Discounts',
  TranslationKeys.specialDeals: 'Special Deals',

  // Auth section
  TranslationKeys.welcomeBack: 'Welcome Back',
  TranslationKeys.pleaseEnterDetailsToSignIn: 'Please enter your details to sign in.',
  TranslationKeys.email: 'Email',
  TranslationKeys.enterYourEmail: 'Enter your email',
  TranslationKeys.emailRequired: 'Email is required',
  TranslationKeys.password: 'Password',
  TranslationKeys.enterYourPassword: 'Enter your password',
  TranslationKeys.passwordRequired: 'Password is required',
  TranslationKeys.rememberMe: 'Remember me',
  TranslationKeys.forgotPassword: 'Forgot password',
  TranslationKeys.loginFailed: 'Login failed',
  TranslationKeys.signIn: 'Sign In',
  TranslationKeys.dontHaveAccount: 'Don\'t have an account? ',
  TranslationKeys.signUp: 'Sign up',
  
  TranslationKeys.createAccount: 'Create Account',
  TranslationKeys.pleaseEnterDetailsToSignUp: 'Please enter your details to sign up.',
  TranslationKeys.firstName: 'First Name',
  TranslationKeys.lastName: 'Last Name',
  TranslationKeys.confirmPassword: 'Confirm Password',
  TranslationKeys.requiredField: 'Required',
  TranslationKeys.createPassword: 'Create a password',
  TranslationKeys.confirmYourPassword: 'Confirm your password',
  TranslationKeys.passwordsDoNotMatch: 'Passwords do not match!',
  TranslationKeys.pleaseAgreeToTerms: 'Please agree to the Terms & Conditions',
  TranslationKeys.iAgreeToThe: 'I agree to the ',
  TranslationKeys.andPrivacyPolicy: ' and Privacy Policy',
  TranslationKeys.alreadyHaveAccount: 'Already have an account? ',
  TranslationKeys.registrationFailed: 'Registration failed',
  
  TranslationKeys.noWorriesResetInstructions: 'No worries, we\'ll send you reset instructions.',
  TranslationKeys.sendResetLink: 'Send Reset Link',
  TranslationKeys.backToLogin: 'Back to log in',
  
  TranslationKeys.passwordReset: 'Password Reset',
  TranslationKeys.passwordResetSuccessMessage: 'Your password has been successfully reset. Click below to log in magically.',
  TranslationKeys.continueToLogin: 'Continue to Login',
  TranslationKeys.setNewPassword: 'Set new password',
  TranslationKeys.newPasswordMustBeDifferent: 'Your new password must be different from previous used passwords.',
  TranslationKeys.mustBeAtLeast8: 'Must be at least 8 characters',
  TranslationKeys.bothPasswordsMustMatch: 'Both passwords must match',
  TranslationKeys.resetPassword: 'Reset Password',
  
  TranslationKeys.orContinueWith: 'Or continue with',
  
  // Profile section
  TranslationKeys.myAccount: 'My Account',
  TranslationKeys.orders: 'Orders',
  TranslationKeys.wishlist: 'Wishlist',
  TranslationKeys.addresses: 'Addresses',
  TranslationKeys.settings: 'Settings',
  TranslationKeys.logout: 'Logout',
  TranslationKeys.switchStore: 'Switch Store',
  TranslationKeys.myStores: 'My Stores',
  TranslationKeys.visits: 'Visits',
  TranslationKeys.ordersCount: 'Orders',
  TranslationKeys.sectionComingSoon: 'Section coming soon!',
  TranslationKeys.profileUpdatedSuccessfully: 'Profile updated successfully!',
  TranslationKeys.accountInformation: 'Account Information',
  TranslationKeys.updateYourPersonalInfo: 'Update your personal information below.',
  TranslationKeys.enterYourFirstName: 'Enter your first name',
  TranslationKeys.enterYourLastName: 'Enter your last name',
  TranslationKeys.emailAddress: 'Email Address',
  TranslationKeys.phoneNumber: 'Phone Number',
  TranslationKeys.enterYourPhoneNumber: 'Enter your phone number',
  TranslationKeys.saveChanges: 'Save Changes',
  
  TranslationKeys.orderHistory: 'Order History',
  TranslationKeys.viewYourRecentOrders: 'View your recent orders and their status.',
  TranslationKeys.noOrdersYet: 'No orders yet',
  TranslationKeys.yourRecentOrdersWillAppearHere: 'Your recent orders will appear here',
  TranslationKeys.statusDelivered: 'Delivered',
  TranslationKeys.statusProcessing: 'Processing',
  TranslationKeys.statusCancelled: 'Cancelled',
  TranslationKeys.viewDetails: 'View Details',

  TranslationKeys.myWishlist: 'My Wishlist',
  TranslationKeys.productsYouHaveSavedForLater: 'Products you have saved for later.',
  TranslationKeys.yourWishlistIsEmpty: 'Your wishlist is empty',
  TranslationKeys.tapHeartToSave: 'Tap the heart icon on a product to save it.',

  TranslationKeys.savedAddresses: 'Saved Addresses',
  TranslationKeys.manageShippingAndBilling: 'Manage your shipping and billing addresses.',
  TranslationKeys.noAddressesFound: 'No addresses found',
  TranslationKeys.addNewAddressPrompt: 'Add a new address to make checkout faster',
  TranslationKeys.addNew: '+ Add New',

  TranslationKeys.appearance: 'Appearance',
  TranslationKeys.theme: 'Theme',
  TranslationKeys.selectApplicationTheme: 'Select application theme',
  TranslationKeys.systemDefault: 'System Default',
  TranslationKeys.light: 'Light',
  TranslationKeys.dark: 'Dark',
  
  TranslationKeys.localization: 'Localization',
  TranslationKeys.language: 'Language',
  TranslationKeys.selectApplicationLanguage: 'Select application language',
  TranslationKeys.english: 'English',
  TranslationKeys.arabic: 'العربية',
  
  TranslationKeys.regional: 'Regional',
  TranslationKeys.currency: 'Currency',
  TranslationKeys.selectPreferredCurrency: 'Select preferred currency',

  TranslationKeys.profile: 'Profile',
  TranslationKeys.menu: 'Menu',
  TranslationKeys.items: 'Items',

  TranslationKeys.byAlzakaaSimpleSolutionsAllRightsReserved: 'by Alzakaa Simple Solutions, All Rights Reserved',

  // Home Page
  TranslationKeys.findClothesThatMatchesYourStyle: 'FIND CLOTHES THAT MATCHES YOUR STYLE',
  TranslationKeys.browseThroughOurDiverseRange: 'Browse through our diverse range of meticulously crafted garments, designed to bring out your individuality and cater to your sense of style.',
  TranslationKeys.fashionModel: 'Fashion Model',
  TranslationKeys.browseByCategory: 'BROWSE BY CATEGORY',
  TranslationKeys.viewAll: 'View All',
  TranslationKeys.stayUptoDate: 'STAY UPTO DATE ABOUT OUR LATEST OFFERS',
  TranslationKeys.subscribeToNewsletter: 'Subscribe to Newsletter',
  TranslationKeys.subscribedSuccessfully: 'Subscribed to Newsletter successfully!',
  TranslationKeys.pleaseLoginToSaveItems: 'Please log in to save items to your wishlist.',

  // Categories & Product Details
  TranslationKeys.allProducts: 'All Products',
  TranslationKeys.productDetails: 'Product Details',
  TranslationKeys.shop: 'Shop',
  TranslationKeys.showingProductsTemplate: 'Showing {start}-{end} of {total} Products',
  TranslationKeys.sortBy: 'Sort by: ',
  TranslationKeys.mostPopular: 'Most Popular',
  TranslationKeys.newest: 'Newest',
  TranslationKeys.priceLowToHigh: 'Price: Low to High',
  TranslationKeys.priceHighToLow: 'Price: High to Low',
  TranslationKeys.filters: 'Filters',
  TranslationKeys.clear: 'Clear',
  TranslationKeys.price: 'Price',
  TranslationKeys.color: 'Color',
  TranslationKeys.colors: 'Colors',
  TranslationKeys.noColorsAvailable: 'No colors available',
  TranslationKeys.size: 'Size',
  TranslationKeys.noSizesAvailable: 'No sizes available',
  TranslationKeys.viewInCart: 'View in Cart',
  TranslationKeys.addToCart: 'Add to Cart',
  TranslationKeys.selectColors: 'Select Colors',
  TranslationKeys.chooseSize: 'Choose Size',
  TranslationKeys.youMightAlsoLike: 'YOU MIGHT ALSO LIKE',
  TranslationKeys.previous: 'Previous',
  TranslationKeys.next: 'Next',
  TranslationKeys.noProductsFound: 'No products found.',

  TranslationKeys.qty: 'Qty',
  // Cart & Checkout
  TranslationKeys.yourCart: 'YOUR CART',
  TranslationKeys.yourCartIsEmpty: 'Your cart is empty',
  TranslationKeys.cartEmptySubtitle: 'Looks like you haven\'t added any items yet.',
  TranslationKeys.itemRemovedFromCart: 'Item removed from cart',
  TranslationKeys.notAvailable: 'N/A',
  TranslationKeys.orderSummary: 'Order Summary',
  TranslationKeys.pricingMultiplied: 'Pricing multiplied by {multiplier} (Due to multiple shipping addresses)',
  TranslationKeys.subtotal: 'Subtotal',
  TranslationKeys.discount: 'Discount (-20%)',
  TranslationKeys.deliveryFee: 'Delivery Fee',
  TranslationKeys.total: 'Total',
  TranslationKeys.placeOrder: 'Place Order',
  TranslationKeys.goToCheckout: 'Go to Checkout',
  TranslationKeys.checkout: 'Checkout',
  TranslationKeys.loginToPlaceOrder: 'Please log in to place an order.',
  TranslationKeys.selectShippingAddress: 'Please select at least one shipping address.',
  TranslationKeys.orderPlacedSuccessfully: 'Order Placed Successfully!',
  TranslationKeys.thankYouForPurchase: 'Thank you for your purchase.\nYour Invoice IDs:\n',
  TranslationKeys.backToHome: 'Back to Home',
  TranslationKeys.checkoutTitle: 'CHECKOUT',
  TranslationKeys.customerInformation: 'Customer Information',
  TranslationKeys.checkingOutAsGuest: 'You are checking out as a Guest.',
  TranslationKeys.login: 'Log In',
  TranslationKeys.noPhoneNumber: 'No Phone Number',
  TranslationKeys.shippingAddress: 'Shipping Address',
  TranslationKeys.loginToManageAddresses: 'Please log in to manage your shipping addresses.',
  TranslationKeys.noSavedAddresses: 'No saved addresses found. Please add a new address.',
  TranslationKeys.addNewAddress: 'Add New Address',
  TranslationKeys.orderItems: 'Order Items ({count})',
  TranslationKeys.addressFallback: 'Address',
  TranslationKeys.paymentMethod: 'Payment Method',
  TranslationKeys.paymentMethodCod: 'Cash on Delivery',
  TranslationKeys.paymentMethodCreditCard: 'Credit Card',
  TranslationKeys.paymentMethodPaypal: 'PayPal',

  // Address Form
  TranslationKeys.editAddress: 'Edit Address',
  TranslationKeys.addressLabelOptional: 'Address Label (Optional)',
  TranslationKeys.egHomeWork: 'e.g. Home, Work',
  TranslationKeys.streetAddress: 'Street Address',
  TranslationKeys.enterStreetAddress: 'Enter street address',
  TranslationKeys.city: 'City',
  TranslationKeys.state: 'State',
  TranslationKeys.zipCode: 'Zip Code',
  TranslationKeys.country: 'Country',
  TranslationKeys.requiredValidation: 'Required',
  TranslationKeys.saveAddress: 'Save Address',

  // Order Details
  TranslationKeys.orderDetails: 'Order Details',
  TranslationKeys.orderNumber: 'Order {id}',
  TranslationKeys.placedOn: 'Placed on {date}',
  TranslationKeys.tax: 'Tax',
  TranslationKeys.defaultText: 'Default',

  // Misc
  TranslationKeys.google: 'Google',
  TranslationKeys.apple: 'Apple',
  TranslationKeys.john: 'John',
  TranslationKeys.doe: 'Doe',
  TranslationKeys.phone: 'Phone',
  TranslationKeys.contactUsDescription: 'We would love to hear from you! Please reach out to us using the details below:',
  TranslationKeys.supportTeamAvailable: 'Our support team is available 24/7 to assist you with any questions or concerns.',
  TranslationKeys.selectStore: 'Select Store',
  TranslationKeys.noStoresAvailable: 'No stores available.',
};
